class CreateCholeskies < ActiveRecord::Migration
  def self.up
    create_table :choleskies do |t|
      t.float :USD_USD_EBITDA
      t.float :USD_GBP_EBITDA
      t.float :USD_EUR_EBITDA
      t.float :USD_YEN_EBITDA
      t.float :USD_BRL_EBITDA
      t.float :USD_fx12_EBITDA
      t.float :USD_fx13_EBITDA
      t.float :USD_fx14_EBITDA
      t.float :USD_fx15_EBITDA 
      t.float :EUR_USD_EBITDA
      t.float :EUR_GBP_EBITDA
      t.float :EUR_EUR_EBITDA
      t.float :EUR_YEN_EBITDA
      t.float :EUR_BRL_EBITDA
      t.float :EUR_fx12_EBITDA
      t.float :EUR_fx13_EBITDA
      t.float :EUR_fx14_EBITDA
      t.float :EUR_fx15_EBITDA 
      t.float :GBP_USD_EBITDA
      t.float :GBP_GBP_EBITDA
      t.float :GBP_EUR_EBITDA
      t.float :GBP_YEN_EBITDA
      t.float :GBP_BRL_EBITDA
      t.float :GBP_fx12_EBITDA
      t.float :GBP_fx13_EBITDA
      t.float :GBP_fx14_EBITDA
      t.float :GBP_fx15_EBITDA
      t.float :YEN_USD_EBITDA
      t.float :YEN_GBP_EBITDA
      t.float :YEN_EUR_EBITDA
      t.float :YEN_YEN_EBITDA
      t.float :YEN_BRL_EBITDA
      t.float :YEN_fx12_EBITDA
      t.float :YEN_fx13_EBITDA
      t.float :YEN_fx14_EBITDA
      t.float :YEN_fx15_EBITDA
      t.float :BRL_USD_EBITDA
      t.float :BRL_GBP_EBITDA
      t.float :BRL_EUR_EBITDA
      t.float :BRL_YEN_EBITDA
      t.float :BRL_BRL_EBITDA
      t.float :BRL_fx12_EBITDA
      t.float :BRL_fx13_EBITDA
      t.float :BRL_fx14_EBITDA
      t.float :BRL_fx15_EBITDA
      t.float :fx12_USD_EBITDA
      t.float :fx12_GBP_EBITDA
      t.float :fx12_EUR_EBITDA
      t.float :fx12_YEN_EBITDA
      t.float :fx12_BRL_EBITDA
      t.float :fx12_fx12_EBITDA
      t.float :fx12_fx13_EBITDA
      t.float :fx12_fx14_EBITDA
      t.float :fx12_fx15_EBITDA
      t.float :fx13_USD_EBITDA
      t.float :fx13_GBP_EBITDA
      t.float :fx13_EUR_EBITDA
      t.float :fx13_YEN_EBITDA
      t.float :fx13_BRL_EBITDA
      t.float :fx13_fx12_EBITDA
      t.float :fx13_fx13_EBITDA
      t.float :fx13_fx14_EBITDA
      t.float :fx13_fx15_EBITDA
      t.float :fx14_USD_EBITDA
      t.float :fx14_GBP_EBITDA
      t.float :fx14_EUR_EBITDA
      t.float :fx14_YEN_EBITDA
      t.float :fx14_BRL_EBITDA
      t.float :fx14_fx12_EBITDA
      t.float :fx14_fx13_EBITDA
      t.float :fx14_fx14_EBITDA
      t.float :fx14_fx15_EBITDA
      t.float :fx15_USD_EBITDA
      t.float :fx15_GBP_EBITDA
      t.float :fx15_EUR_EBITDA
      t.float :fx15_YEN_EBITDA
      t.float :fx15_BRL_EBITDA
      t.float :fx15_fx12_EBITDA
      t.float :fx15_fx13_EBITDA
      t.float :fx15_fx14_EBITDA
      t.float :fx15_fx15_EBITDA
      t.timestamps
    end
  end

  def self.down
    drop_table :choleskies
  end
end
